# Python NumPy Exercises: 50 Coding Problems with Solutions

A practice notebook on NumPy array creation, indexing/slicing, boolean masking, reshaping, aggregation, and linear algebra — each with a concept note, a hint, a solution, and an explanation.

*Adapted for practice from the exercise list at [PYnative](https://pynative.com/python-numpy-exercise/). The source page has several internal inconsistencies — mismatched given/expected data in a few exercises, and exercises 49–50 appear to have copy-paste content from earlier exercises — all fixed here with self-consistent versions that keep each exercise's original topic and intent.*

---

## Concepts you'll need

This set covers **NumPy**, the core array library for numerical computing in Python.

- **Creating arrays** — `np.array(list)`, `np.arange(n)` (like `range()` but returns an array), `np.zeros()`/`np.ones()`/`np.full()`, `np.eye(n)` (identity matrix), `np.linspace(start, stop, num)` (evenly spaced values, *inclusive* of both ends), `np.random.rand()`/`randint()`.
- **Array attributes** — `.shape` (dimensions as a tuple), `.ndim` (number of dimensions), `.dtype` (element type), `.itemsize` (bytes per element), `.nbytes` (total memory).
- **Indexing & slicing** — works like Python lists but extends to multiple dimensions with a comma: `arr[row, col]`, `arr[:, -1]` (last column), `arr[1::2, ::2]` (every-other rows/columns). Slicing returns a *view* (shares memory), not a copy.
- **Boolean masking** — `arr[arr > 5]` filters using a condition; combine conditions with `&` (and) / `|` (or), each condition in its own parentheses; assignment through a mask (`arr[mask] = value`) modifies in place.
- **Reshaping & combining** — `.reshape(rows, cols)`, `.flatten()` (copy) / `.ravel()` (view), `np.hstack()`/`vstack()` (combine arrays), `np.split()` (divide into equal parts).
- **Element-wise vs. matrix operations** — `+`, `-`, `*`, `/`, `**` all operate element-by-element automatically ("vectorization" — no loop needed); `np.dot()` / `@` is real matrix multiplication, a fundamentally different operation from `*`.
- **Set-like operations** — `np.unique()`, `np.intersect1d()`, `np.union1d()`, `np.in1d()` (membership test) treat arrays like mathematical sets.
- **Aggregations** — `np.mean()`, `np.median()`, `np.std()`, `np.min()`/`max()`, often combined with `axis=` to aggregate along rows (`axis=1`) or columns (`axis=0`) instead of the whole array.
- **Linear algebra** — `np.linalg.inv()` (matrix inverse), `np.linalg.eig()` (eigenvalues/eigenvectors), `np.linalg.solve(A, b)` (solves `Ax = b` directly, better than computing an inverse manually).

Each exercise below gives a problem, a hint, a solution, and an explanation.

## Exercise 1. Create a 1D Array of Numbers 0-9

**Concept:** np.arange()

**Problem:** Create a 1D NumPy array containing the numbers 0 through 9.

**Given:**
```
no input
```

**Expected Output:**
```
[0 1 2 3 4 5 6 7 8 9]
```

**Hint:** np.arange(10) behaves like range(10) but returns an array directly.

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

**Explanation:** np.arange(10) generates values from 0 up to (but not including) 10, with a default step of 1 — directly analogous to Python's built-in range(), but returning an actual NumPy array rather than a lazy range object.

## Exercise 2. Convert 1D Array to 2D

**Concept:** .reshape()

**Problem:** Convert a 1D array of 6 elements into a 2D array with 2 rows.

**Given:**
```
arr = np.arange(6)
```

**Expected Output:**
```
Original: [0 1 2 3 4 5]
Reshaped 2x3:
 [[0 1 2]
  [3 4 5]]
```

**Hint:** reshape(rows, cols) needs rows * cols to exactly equal the original element count.

In [ ]:
import numpy as np

arr = np.arange(6)
print("Original Array:", arr)

arr_2d = arr.reshape(2, 3)
print("Reshaped 2x3 Array:\n", arr_2d)

**Explanation:** reshape() gives the array a new shape without altering any of its underlying data. Since the original array has 6 elements and 2 rows are requested, NumPy requires 3 columns to make the total match (2 x 3 = 6) — asking for a shape whose product doesn't equal 6 would raise a ValueError.

## Exercise 3. Print Array Attributes

**Concept:** .shape, .ndim, .itemsize

**Problem:** Print the shape, number of dimensions, and per-element byte size of an array.

**Given:**
```
my_array = np.array([[1,2],[3,4],[5,6],[7,8]], dtype=np.uint16)
```

**Expected Output:**
```
The shape of the array is: (4, 2)
The number of dimensions is: 2
The size of each element in bytes is: 2
```

**Hint:** dtype=np.uint16 explicitly forces a fixed 16-bit (2-byte) unsigned integer type.

In [ ]:
import numpy as np

my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print("The shape of the array is:", my_array.shape)
print("The number of dimensions is:", my_array.ndim)
print("The size of each element in bytes is:", my_array.itemsize)

**Explanation:** .shape reports the array's dimensions as a tuple — (4, 2) means 4 rows and 2 columns. .ndim reports how many axes the array has (2 for a matrix). .itemsize reports the byte size of a SINGLE element, which is fixed by the dtype — np.uint16 is a 16-bit unsigned integer, occupying exactly 2 bytes regardless of the value stored.

## Exercise 4. Create a 3x3 Array of All True

**Concept:** np.ones() with dtype=bool

**Problem:** Create a 3x3 NumPy array filled entirely with the boolean value True.

**Given:**
```
no input
```

**Expected Output:**
```
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
```

**Hint:** np.ones() with dtype=bool interprets every 1 as True.

In [ ]:
import numpy as np

arr = np.ones((3, 3), dtype=bool)
print(arr)

**Explanation:** np.ones((3, 3)) creates a 3x3 array filled with 1s; passing dtype=bool tells NumPy to interpret and store those values as booleans instead of floats, so every 1 becomes True. np.full((3, 3), True) would achieve the identical result more directly, by specifying the fill value explicitly rather than relying on 1's truthiness.

## Exercise 5. Extract the Documentation of arange()

**Concept:** np.info()

**Problem:** Display the built-in documentation for NumPy's arange() function.

**Given:**
```
no input
```

**Expected Output:**
```
arange([start,] stop[, step,], dtype=None, *, like=None)
... (full docstring)
```

**Hint:** np.info() prints a function's docstring directly to the console.

In [ ]:
import numpy as np

np.info(np.arange)

**Explanation:** np.info() looks up and prints the docstring of whatever object is passed to it — functions, classes, or even NumPy dtypes — covering usage, parameters, and return type. It's a fast way to check a function's exact signature and behavior without leaving the interpreter to search documentation online.

## Exercise 6. Create 1D Arrays of Zeros and Ones

**Concept:** np.zeros() and np.ones()

**Problem:** Create a 1D array filled with zeros and another filled with ones, both length 5.

**Given:**
```
no input
```

**Expected Output:**
```
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
```

**Hint:** Both functions default to a float dtype, hence the decimal points in the output.

In [ ]:
import numpy as np

zeros_arr = np.zeros(5)
ones_arr = np.ones(5)

print("Zeros:", zeros_arr)
print("Ones:", ones_arr)

**Explanation:** np.zeros(5) and np.ones(5) both allocate a 1D array of the given length, filled entirely with 0.0 or 1.0 respectively. The default dtype for both is float64, which is why the output shows decimal points (0. rather than a plain integer 0) — passing dtype=int would produce whole numbers instead.

## Exercise 7. 10 Evenly Spaced Values Between 5 and 50

**Concept:** np.linspace()

**Problem:** Create a 1D array of 10 evenly spaced values between 5 and 50, inclusive of both ends.

**Given:**
```
no input
```

**Expected Output:**
```
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
```

**Hint:** Unlike arange(), linspace()'s stop value IS included by default.

In [ ]:
import numpy as np

arr = np.linspace(5, 50, 10)
print(arr)

**Explanation:** np.linspace(start, stop, num) generates exactly num values spread evenly across the [start, stop] interval, with BOTH endpoints included by default — a key difference from np.arange(), where the stop value is excluded. This makes linspace() the natural choice when you know exactly how many points you want, rather than what step size to use.

## Exercise 8. Convert a Python List to a NumPy Array

**Concept:** np.array()

**Problem:** Convert a plain Python list into a NumPy array.

**Given:**
```
py_list = [1, 2, 3, 4, 5]
```

**Expected Output:**
```
[1 2 3 4 5]
```

**Hint:** np.array() accepts any Python list (or nested list) directly.

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
arr = np.array(py_list)
print(arr)

**Explanation:** np.array() converts a Python list (or a nested list, for multi-dimensional arrays) into a NumPy array, unlocking vectorized math operations, broadcasting, and the rest of NumPy's functionality that plain Python lists don't support directly.

## Exercise 9. Find the Memory Size of an Array

**Concept:** .nbytes

**Problem:** Find the total memory (in bytes) used by an array of numbers 0-9.

**Given:**
```
no input
```

**Expected Output:**
```
Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes: 80
```

**Hint:** .nbytes is simply .itemsize multiplied by the total element count.

In [ ]:
import numpy as np

arr = np.arange(10)
print("Array:", arr)
print("Memory size in bytes:", arr.nbytes)

**Explanation:** Each element in a NumPy array occupies a fixed number of bytes determined by its dtype (here, the default integer type is 8 bytes on most 64-bit systems). .nbytes reports the array's TOTAL memory footprint, equal to itemsize x number of elements — 8 bytes x 10 elements = 80 bytes.

## Exercise 10. Reverse a 1D NumPy Array

**Concept:** slicing with [::-1]

**Problem:** Reverse the order of elements in a 1D array.

**Given:**
```
arr = np.arange(10)
```

**Expected Output:**
```
[9 8 7 6 5 4 3 2 1 0]
```

**Hint:** The same [::-1] slicing trick that reverses Python lists and strings works identically on NumPy arrays.

In [ ]:
import numpy as np

arr = np.arange(10)
reversed_arr = arr[::-1]
print(reversed_arr)

**Explanation:** [::-1] is a slice with no explicit start or stop, and a step of -1, which tells NumPy to walk the array from the last element to the first. This is the same slicing syntax that works on plain Python lists and strings, extended naturally to NumPy arrays.

## Exercise 11. Create a 3x3 Identity Matrix

**Concept:** np.eye()

**Problem:** Create a 3x3 identity matrix (1s on the diagonal, 0s elsewhere).

**Given:**
```
no input
```

**Expected Output:**
```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

**Hint:** np.eye(n) is the dedicated function for identity matrices — no manual diagonal-filling needed.

In [ ]:
import numpy as np

identity = np.eye(3)
print(identity)

**Explanation:** An identity matrix has 1s running down its main diagonal (top-left to bottom-right) and 0s everywhere else — the matrix equivalent of the number 1, since multiplying any compatible matrix by it leaves that matrix unchanged. np.eye(3) builds exactly this pattern directly for a 3x3 matrix, with no manual index-based filling required.

## Exercise 12. Create a 4x4 Array and Extract First Row/Last Column

**Concept:** row indexing [0] and column slicing [:, -1]

**Problem:** Create a 4x4 array of 1-16 and extract its first row and last column.

**Given:**
```
no input
```

**Expected Output:**
```
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]
```

**Hint:** arr[0] gets the first row; arr[:, -1] means 'every row, last column'.

In [ ]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)

first_row = arr[0]
print("First Row:", first_row)

last_col = arr[:, -1]
print("Last Column:", last_col)

**Explanation:** np.arange(1, 17).reshape(4, 4) builds a 4x4 grid containing 1 through 16. arr[0] indexes the first row directly, just like indexing the first element of a list of lists. arr[:, -1] uses two-dimensional indexing — the : before the comma means 'every row', and -1 after the comma means 'the last column' — together selecting one value from each row, all from the rightmost column.

## Exercise 13. Extract Odd Rows and Even Columns

**Concept:** combined row/column step-slicing

**Problem:** Extract the elements at odd-indexed rows and even-indexed columns.

**Given:**
```
a 5x4 array of multiples of 3
```

**Expected Output:**
```
[[15 21]
 [39 45]]
```

**Hint:** sampleArray[1::2, ::2] combines a row slice and a column slice in one indexing operation.

In [ ]:
import numpy as np

sampleArray = np.array([
    [3, 6, 9, 12],
    [15, 18, 21, 24],
    [27, 30, 33, 36],
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])

newArray = sampleArray[1::2, ::2]

print("Original Array:")
print(sampleArray)
print("\nNew Array with Odd Rows and Even Columns:")
print(newArray)

**Explanation:** 1::2 for the row slice starts at index 1 (the second row) and steps by 2, selecting rows at indices 1 and 3 — the odd-indexed rows. ::2 for the column slice starts at index 0 (the default) and also steps by 2, selecting columns at indices 0 and 2 — the even-indexed columns. Combining both slices with a comma, sampleArray[1::2, ::2], selects exactly the intersection: the values sitting at an odd row AND an even column simultaneously.

## Exercise 14. Stack Arrays Horizontally

**Concept:** np.hstack()

**Problem:** Join two 1D arrays end-to-end into one array.

**Given:**
```
a = [1,2,3], b = [4,5,6]
```

**Expected Output:**
```
[1 2 3 4 5 6]
```

**Hint:** For 1D arrays, hstack() is equivalent to simple concatenation.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.hstack((a, b))
print(stacked_arr)

**Explanation:** np.hstack() ('horizontal stack') joins arrays along their second axis (columns) — but for plain 1D arrays, which have no real second axis, this simplifies to joining them end-to-end into one longer 1D array. For higher-dimensional arrays, hstack() would instead place the arrays side by side as new columns.

## Exercise 15. Slice First Two Rows and Columns

**Concept:** two-dimensional range slicing

**Problem:** Extract the first two rows and first two columns from a 4x4 array as a 2x2 sub-array.

**Given:**
```
no input
```

**Expected Output:**
```
First 2 rows and columns:
 [[1 2]
  [5 6]]
```

**Hint:** arr[0:2, 0:2] selects rows 0-1 and columns 0-1 simultaneously.

In [ ]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)

sub_arr = arr[0:2, 0:2]
print("First 2 rows and columns:\n", sub_arr)

**Explanation:** arr[0:2, 0:2] applies a row slice (0:2, meaning rows 0 and 1) and a column slice (0:2, meaning columns 0 and 1) together in one indexing operation, extracting the 2x2 block sitting in the array's top-left corner.

## Exercise 16. Replace All Odd Numbers with -1

**Concept:** boolean masking combined with in-place assignment

**Problem:** Replace every odd number in an array with -1.

**Given:**
```
arr = np.arange(1, 11)
```

**Expected Output:**
```
Original: [ 1  2  3  4  5  6  7  8  9 10]
Modified: [-1  2 -1  4 -1  6 -1  8 -1 10]
```

**Hint:** arr[mask] = value assigns to exactly the positions where mask is True, modifying the array in place.

In [ ]:
import numpy as np

arr = np.arange(1, 11)
print("Original Array:", arr)

arr[arr % 2 == 1] = -1
print("Modified Array:", arr)

**Explanation:** arr % 2 == 1 is evaluated element-wise across the whole array, producing a boolean mask that's True at every odd position. Using that mask as an index — arr[mask] = -1 — assigns -1 to exactly those positions, modifying the original array directly rather than returning a new one.

## Exercise 17. Get Indices of Non-Zero Elements

**Concept:** np.nonzero()

**Problem:** Find the indices of every non-zero element in an array.

**Given:**
```
arr = np.array([1, 0, 2, 0, 3, 0, 4])
```

**Expected Output:**
```
Indices: (array([0, 2, 4, 6]),)
```

**Hint:** np.nonzero() returns a TUPLE of index arrays (one per dimension), even for a 1D input.

In [ ]:
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 0, 4])
print("Array:", arr)

indices = np.nonzero(arr)
print("Indices of non-zero elements:", indices)

**Explanation:** np.nonzero() returns a tuple containing one array of indices per dimension of the input — for a 1D array, that's a single-element tuple holding the index array. Here, non-zero values (1, 2, 3, 4) sit at positions 0, 2, 4, and 6, which is exactly what's reported; for a 2D array, this same function would return a pair of arrays giving the row and column of each non-zero element.

## Exercise 18. Find Common Items Between Two Arrays

**Concept:** np.intersect1d()

**Problem:** Find the elements shared between two arrays.

**Given:**
```
a = [1,2,3,2,8,4,2,4], b = [2,4,5,6,8]
```

**Expected Output:**
```
[2 4 8]
```

**Hint:** intersect1d() automatically deduplicates and sorts its result.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])
common_items = np.intersect1d(a, b)
print(common_items)

**Explanation:** np.intersect1d() finds the elements present in BOTH input arrays, returning them as a sorted array with duplicates removed — even though 2 and 4 both repeat multiple times in a, each appears only once in the result. This is a fast, vectorized set-intersection operation, far more efficient on large arrays than writing a manual comparison loop.

## Exercise 19. Element-wise Arithmetic on Two Arrays

**Concept:** vectorized + and * operators

**Problem:** Add and multiply two arrays element-by-element.

**Given:**
```
a = [1,2,3], b = [4,5,6]
```

**Expected Output:**
```
Element-wise Sum: [5 7 9]
Element-wise multiplication: [ 4 10 18]
```

**Hint:** + and * on NumPy arrays act element-wise automatically — no loop needed.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add = a + b
print("Element-wise Sum:", add)

product = a * b
print("Element-wise multiplication:", product)

**Explanation:** Unlike plain Python lists (where + concatenates and * repeats), NumPy overloads these operators to work element-wise by default across same-shaped arrays — a[i] + b[i] and a[i] * b[i] for every position i, all computed in a single vectorized pass rather than a Python-level loop, which is dramatically faster for large arrays.

## Exercise 20. Matrix Multiplication (Dot Product)

**Concept:** np.dot() / @ — distinct from element-wise *

**Problem:** Compute the dot product of two 1D arrays.

**Given:**
```
a = [1,2,3], b = [4,5,6]
```

**Expected Output:**
```
Dot Product: 32
```

**Hint:** np.dot() and the @ operator both perform TRUE matrix multiplication, unlike element-wise *.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
print("Dot Product:", dot_product)
print("Using @ operator:", a @ b)

**Explanation:** It's crucial to distinguish np.dot()/@ (true matrix multiplication, following linear algebra rules) from the element-wise * operator, which is an entirely different operation. For two 1D vectors, the dot product sums the products of corresponding elements: 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32. For 2D matrices, @ instead computes full matrix multiplication, where each output cell is the dot product of one row from the first matrix and one column from the second.

## Exercise 21. Compute Mean, Median, and Standard Deviation

**Concept:** np.mean(), np.median(), np.std()

**Problem:** Compute the mean, median, and standard deviation of an array.

**Given:**
```
arr = np.array([10, 20, 30, 100, 200, 300])
```

**Expected Output:**
```
Mean: 110.0
Median: 65.0
Standard Deviation: 107.08252269472673
```

**Hint:** np.median() sorts internally and averages the two middle values for an even-length array.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 100, 200, 300])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

**Explanation:** np.mean() sums every element and divides by the count — (10+20+30+100+200+300)/6 = 110.0. np.median() sorts the data internally and, for this even-length (6-element) array, averages the two middle values (30 and 100), giving 65.0. np.std() measures spread around the mean; by default it computes the POPULATION standard deviation (dividing by n), not the sample standard deviation (dividing by n-1) — pass ddof=1 if the sample version is specifically needed.

## Exercise 22. Remove Common Items from an Array

**Concept:** np.in1d() (membership test) combined with the ~ NOT operator

**Problem:** Remove from array a every element that also appears in array b.

**Given:**
```
a = [1,2,3,4,5], b = [5,6,7,8,9]
```

**Expected Output:**
```
[1 2 3 4]
```

**Hint:** ~ is the bitwise NOT operator — it flips every True to False and vice versa in a boolean mask.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

mask = np.isin(a, b)
result = a[~mask]
print(result)

**Explanation:** np.isin(a, b) (the modern name for the same functionality as the older np.in1d()) checks each element of a for membership in b, returning a boolean array — True at position i means a[i] is also somewhere in b. ~mask inverts every value in that boolean array (True becomes False and vice versa) via the bitwise NOT operator, so a[~mask] selects exactly the elements of a that are NOT found in b.

## Exercise 23. Normalize an Array to [0, 1]

**Concept:** min-max normalization

**Problem:** Rescale an array's values so the minimum becomes 0 and the maximum becomes 1.

**Given:**
```
arr = [10, 20, 30, 40, 50]
```

**Expected Output:**
```
Normalized Array: [0.   0.25 0.5  0.75 1.  ]
```

**Hint:** Subtracting the min shifts the smallest value to 0; dividing by the range scales the largest value to 1.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized Array:", normalized)

**Explanation:** Subtracting arr.min() from every element shifts the whole array so its smallest value becomes exactly 0. Dividing by the range (arr.max() - arr.min()) then rescales everything so the largest value lands at exactly 1 — every other value falls proportionally in between. Both operations broadcast automatically across the whole array with no explicit loop.

## Exercise 24. Find Positions Where Two Arrays Match

**Concept:** np.where() with a boolean condition

**Problem:** Find the indices where two arrays have equal values at the same position.

**Given:**
```
a = [1,2,3,4,5], b = [1,4,3,7,8]
```

**Expected Output:**
```
(array([0, 2]),)
```

**Hint:** np.where(condition) with just one argument returns the indices where the condition is True.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

index = np.where(a == b)
print(index)

**Explanation:** a == b compares the two arrays element-wise, producing a boolean array (True wherever the corresponding elements match: positions 0 and 2 here, since 1==1 and 3==3). np.where(), when given only a condition (no additional true/false-value arguments), returns the indices where that condition holds — the same tuple-of-arrays format as np.nonzero().

## Exercise 25. Extract Numbers in a Range

**Concept:** combining boolean masks with the & (AND) operator

**Problem:** Extract all numbers from an array that fall between 5 and 10, inclusive.

**Given:**
```
arr = np.arange(15)
```

**Expected Output:**
```
[ 5  6  7  8  9 10]
```

**Hint:** Each comparison must be in its own parentheses when combined with & — Python's operator precedence requires it.

In [ ]:
import numpy as np

arr = np.arange(15)
result = arr[(arr >= 5) & (arr <= 10)]
print(result)

**Explanation:** Two separate boolean masks — arr >= 5 and arr <= 10 — are combined with the bitwise AND operator &, producing a combined mask that's True only where BOTH conditions hold simultaneously. The parentheses around each individual comparison are mandatory here, since & has higher precedence than the comparison operators, and omitting them would produce a syntax or logic error.

## Exercise 26. Random 3x2 Matrix and Its Max/Min

**Concept:** np.random.rand()

**Problem:** Create a random 3x2 matrix of values in [0,1) and find its maximum and minimum.

**Given:**
```
no input (values vary each run)
```

**Expected Output:**
```
A 3x2 matrix, with Max Value and Min Value printed (values vary by run)
```

**Hint:** np.random.rand(rows, cols) draws from a uniform distribution over [0, 1).

In [ ]:
import numpy as np

rand_arr = np.random.rand(3, 2)
print(rand_arr)

print("Max Value:", rand_arr.max())
print("Min Value:", rand_arr.min())

**Explanation:** np.random.rand(3, 2) creates a 3x2 array filled with random floats drawn from a uniform distribution over [0, 1) — 0 is a possible value, 1 is not. .max() and .min() scan the whole array (across both dimensions by default) to report its largest and smallest values.

## Exercise 27. Sort a 2D Array by a Specific Column

**Concept:** np.argsort() applied to one column, then used to reorder all rows

**Problem:** Sort the rows of a 2D array based on the values in its second column.

**Given:**
```
sampleArray = [[34,43,73],[82,22,12],[53,94,66]]
```

**Expected Output:**
```
Sorted array:
[[82 22 12]
 [34 43 73]
 [53 94 66]]
```

**Hint:** argsort() doesn't sort the column itself — it returns the INDICES that WOULD sort it, which you then apply to the whole array.

In [ ]:
import numpy as np

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

sorted_indices = sampleArray[:, 1].argsort()
sorted_array = sampleArray[sorted_indices]

print("Original array:")
print(sampleArray)
print("\nSorted array:")
print(sorted_array)

**Explanation:** sampleArray[:, 1] selects the entire second column (43, 22, 94). .argsort() on that column doesn't sort those values directly — it returns the INDICES that would put them in sorted order: [1, 0, 2], since 22 (index 1) is smallest, then 43 (index 0), then 94 (index 2). Using those indices to reorder the full array, sampleArray[sorted_indices], reorders every ROW to match — moving whole rows together rather than just the column's own values.

## Exercise 28. Delete and Insert a Column

**Concept:** np.delete() and np.insert() with axis=1

**Problem:** Delete the second column of an array and insert a new column in its place.

**Given:**
```
sampleArray, newColumnToAdd = [10, 10, 10]
```

**Expected Output:**
```
[[34 10 73]
 [82 10 12]
 [53 10 66]]
```

**Hint:** axis=1 tells both functions to operate on columns rather than rows.

In [ ]:
import numpy as np

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([10, 10, 10])

deletedArray = np.delete(sampleArray, 1, axis=1)
resultArray = np.insert(deletedArray, 1, newColumn, axis=1)

print(resultArray)

**Explanation:** np.delete(sampleArray, 1, axis=1) removes the column at index 1 (the second column); axis=1 is what tells NumPy 'operate on columns', since without it the function would default to treating the array as flat. np.insert(deletedArray, 1, newColumn, axis=1) then inserts newColumn at position 1 in the now-3-column-short array, again using axis=1 to insert a full column rather than scattering individual values — NumPy automatically broadcasts the 1D newColumn to fit the correct shape.

## Exercise 29. Swap Two Columns in a 2D Array

**Concept:** advanced (fancy) indexing with a list of column indices

**Problem:** Swap columns 1 and 2 of a 3x3 array.

**Given:**
```
arr = np.arange(9).reshape(3, 3)
```

**Expected Output:**
```
Before:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After:
[[0 2 1]
 [3 5 4]
 [6 8 7]]
```

**Hint:** arr[:, [1,2]] = arr[:, [2,1]] reassigns both columns simultaneously in one statement.

In [ ]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Before")
print(arr)

arr[:, [1, 2]] = arr[:, [2, 1]]
print("After")
print(arr)

**Explanation:** arr[:, [1, 2]] uses a LIST of indices (rather than a slice) to select columns 1 and 2 specifically — this is 'fancy indexing'. Assigning arr[:, [2, 1]] (the same two columns, but requested in reverse order) into that selection swaps their data in a single statement: NumPy reads the right-hand side fully before writing, so this works correctly rather than corrupting the data through a partial overwrite.

## Exercise 30. Generate 10 Random Integers Between 1 and 100

**Concept:** np.random.randint()

**Problem:** Generate 10 random integers in the range 1 to 100, inclusive.

**Given:**
```
no input (values vary each run)
```

**Expected Output:**
```
10 random integers between 1 and 100 (varies by run)
```

**Hint:** np.random.randint(low, high, size) has an EXCLUSIVE high bound, so high must be 101 to include 100.

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, size=10)
print("Random Integers:", arr)

**Explanation:** np.random.randint(low, high, size) draws size integers from the half-open interval [low, high) — high itself is EXCLUDED. To include 100 as a possible value, the high argument must be 101, not 100; this exclusive-upper-bound convention matches Python's own range() and NumPy's arange().

## Exercise 31. Sort a 3x3 Random Array Row-wise

**Concept:** np.sort() with axis=1

**Problem:** Create a 3x3 array of random integers and sort each row independently.

**Given:**
```
no input (values vary each run)
```

**Expected Output:**
```
Each row sorted in ascending order independently (varies by run)
```

**Hint:** axis=1 sorts each row on its own; axis=0 would instead sort each column independently.

In [ ]:
import numpy as np

arr = np.random.randint(1, 50, size=(3, 3))
print("Original Array:\n", arr)

sorted_arr = np.sort(arr, axis=1)
print("Row-wise Sorted Array:\n", sorted_arr)

**Explanation:** np.sort(arr, axis=1) sorts along axis 1 (the columns-within-a-row direction), meaning each ROW is sorted independently and in isolation from the other rows — the relative order of the rows themselves stays unchanged. Passing axis=0 instead would sort each column independently, top to bottom, which produces a very different (and often nonsensical, since it mixes unrelated rows) result.

## Exercise 32. Shuffle an Array Randomly

**Concept:** np.random.shuffle() — in-place shuffling

**Problem:** Randomly shuffle the elements of an array.

**Given:**
```
arr = np.arange(10)
```

**Expected Output:**
```
Shuffled Array: a random permutation of 0-9 (varies by run)
```

**Hint:** shuffle() modifies the array in place and returns None — it doesn't return the shuffled array.

In [ ]:
import numpy as np

arr = np.arange(10)
print("Original Array:", arr)

np.random.shuffle(arr)
print("Shuffled Array:", arr)

**Explanation:** np.random.shuffle() reorders an array's elements randomly IN PLACE, directly modifying the original array object rather than returning a new shuffled copy — which is why the code calls it as a standalone statement (np.random.shuffle(arr)) rather than assigning its result to a variable. Every run produces a different, independently random ordering.

## Exercise 33. 5x5 Array With 1s on the Border and 0s Inside

**Concept:** slicing the interior of an array with [1:-1, 1:-1]

**Problem:** Create a 5x5 array with 1s forming the border and 0s filling the interior.

**Given:**
```
no input
```

**Expected Output:**
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

**Hint:** 1:-1 means 'start at index 1, stop before the last index' — exactly the interior, excluding the border on both ends.

In [ ]:
import numpy as np

arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

**Explanation:** np.ones((5, 5)) starts with every cell set to 1. The slice 1:-1 means 'from index 1 up to (not including) the last index' — applied to both rows and columns simultaneously via arr[1:-1, 1:-1], this addresses exactly the interior 3x3 block, excluding the outermost row and column on every side. Assigning 0 to that selection zeroes out only the interior, leaving the 1-filled border untouched.

## Exercise 34. Check if an Array Contains Any NaN Values

**Concept:** np.isnan() combined with .any()

**Problem:** Check whether an array contains any NaN (Not a Number) values.

**Given:**
```
a = np.array([1, 2, np.nan, 4, 5])
```

**Expected Output:**
```
True
```

**Hint:** np.isnan() produces a boolean array; .any() collapses it to a single True/False.

In [ ]:
import numpy as np

a = np.array([1, 2, np.nan, 4, 5])
has_nan = np.isnan(a).any()
print(has_nan)

**Explanation:** np.isnan(a) checks each element individually and returns a boolean array, True wherever that position holds NaN. .any() then collapses that whole boolean array down to a single True if AT LEAST ONE element was True, or False if none were — a concise way to answer a yes/no question about an entire array without writing a manual loop.

## Exercise 35. Sort Rows by the Second Column (Different Array)

**Concept:** the same argsort()-then-reindex pattern, applied again

**Problem:** Sort the rows of another 2D array based on its second column's values.

**Given:**
```
arr = [[8,4,1],[5,2,7],[6,9,3]]
```

**Expected Output:**
```
[[5 2 7]
 [8 4 1]
 [6 9 3]]
```

**Hint:** Same pattern as Exercise 27: argsort() the target column, then index the full array with the result.

In [ ]:
import numpy as np

arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])

sorted_indices = arr[:, 1].argsort()
sorted_arr = arr[sorted_indices]
print(sorted_arr)

**Explanation:** arr[:, 1] pulls out the second column (4, 2, 9). Its argsort() gives the index order that would sort it: [1, 0, 2] (since 2 < 4 < 9). Applying that same index order to the FULL array — arr[sorted_indices] — reorders entire rows, not just the column values in isolation, which is exactly why the whole row [5, 2, 7] (not just its 2) moves to the top of the result.

## Exercise 36. Flatten a Multi-Dimensional Array

**Concept:** .flatten() (copy) vs. .ravel() (view)

**Problem:** Convert a 2D array into a 1D array.

**Given:**
```
arr = [[1,2],[3,4],[5,6]]
```

**Expected Output:**
```
Flattened Array: [1 2 3 4 5 6]
```

**Hint:** flatten() always returns a genuine independent copy; ravel() may return a view sharing memory with the original.

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
flattened = arr.flatten()

print("Original Array:\n", arr)
print("Flattened Array:", flattened)

**Explanation:** flatten() collapses an array of any number of dimensions down into a single 1D array, always returning a genuinely independent COPY — modifying the flattened result never affects the original array. .ravel() achieves the same visual result but may instead return a VIEW that shares the same underlying memory as the original when possible, which is faster but means modifying it could also modify the source array.

## Exercise 37. Stack Two Arrays Vertically and Horizontally

**Concept:** np.vstack() vs. np.hstack()

**Problem:** Stack two 1D arrays both vertically (as rows) and horizontally (end-to-end).

**Given:**
```
a = [1,2,3], b = [4,5,6]
```

**Expected Output:**
```
Vertical Stack:
 [[1 2 3]
  [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
```

**Hint:** vstack() adds a new dimension (stacking as separate rows); hstack() concatenates within the existing dimension.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack = np.vstack((a, b))
h_stack = np.hstack((a, b))

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)

**Explanation:** np.vstack() stacks arrays row-wise (top to bottom), which for two 1D inputs produces a genuinely new 2D array where each original array becomes its own row. np.hstack() instead stacks column-wise (side by side), which for two 1D inputs simply concatenates them end-to-end into one longer 1D array, as seen back in Exercise 14.

## Exercise 38. Split an Array Into 3 Equal Parts

**Concept:** np.split()

**Problem:** Split a 1D array of 9 elements into 3 equal-sized parts.

**Given:**
```
arr = np.arange(9)
```

**Expected Output:**
```
Split Arrays: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
```

**Hint:** np.split() requires the array length to divide evenly by the requested number of parts, or it raises an error.

In [ ]:
import numpy as np

arr = np.arange(9)
split_arr = np.split(arr, 3)

print("Original Array:", arr)
print("Split Arrays:", split_arr)

**Explanation:** np.split(arr, 3) divides the array into exactly 3 equal-sized pieces, returned as a Python list of smaller NumPy arrays. This only works cleanly when the total length (9) divides evenly by the requested part count (3) — for unequal splits, np.array_split() is the more flexible alternative that tolerates a remainder.

## Exercise 39. Perform Addition and Squaring on Arrays

**Concept:** vectorized + and ** on 2D arrays

**Problem:** Add two 2D arrays together, then square every element of the result.

**Given:**
```
arrayOne and arrayTwo, both 2x3
```

**Expected Output:**
```
Sum:
[[20 39 33]
 [25 25 28]]
Squared:
[[ 400 1521 1089]
 [ 625  625  784]]
```

**Hint:** Both + and ** operate element-wise automatically, extending naturally from 1D to 2D arrays.

In [ ]:
import numpy as np

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

resultArray = arrayOne + arrayTwo
print("Result of array addition:")
print(resultArray)

squaredArray = resultArray ** 2
print("\nResult with each element squared:")
print(squaredArray)

**Explanation:** + between two equally-shaped 2D arrays adds corresponding elements position by position, exactly as it does for 1D arrays — no special handling is needed for the extra dimension. ** 2 similarly squares every individual element of the resulting array in one vectorized operation, with no explicit loop over rows and columns required.

## Exercise 40. Invert a Matrix

**Concept:** np.linalg.inv()

**Problem:** Compute the inverse of a 2x2 matrix.

**Given:**
```
arr = [[1,2],[3,4]]
```

**Expected Output:**
```
[[-2.   1. ]
 [ 1.5 -0.5]]
```

**Hint:** A matrix multiplied by its own inverse yields the identity matrix.

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
inv_arr = np.linalg.inv(arr)
print(inv_arr)

print("\nVerification (arr @ inv_arr should be the identity matrix):")
print(np.round(arr @ inv_arr, 10))

**Explanation:** np.linalg.inv() computes a square matrix's inverse — the unique matrix that, when multiplied by the original (via true matrix multiplication, @), produces the identity matrix. This only works for square matrices whose determinant is non-zero ('invertible' or 'non-singular' matrices); attempting to invert a singular matrix raises a LinAlgError.

## Exercise 41. Filter Values Less Than a Given Number

**Concept:** boolean indexing with a single comparison

**Problem:** Return only the values from an array that are less than 30.

**Given:**
```
arr = [5, 12, 29, 30, 44, 7, 18]
```

**Expected Output:**
```
Values < 30: [ 5 12 29  7 18]
```

**Hint:** arr < 30 alone produces a full boolean mask ready to index with.

In [ ]:
import numpy as np

arr = np.array([5, 12, 29, 30, 44, 7, 18])
filtered = arr[arr < 30]
print("Values < 30:", filtered)

**Explanation:** arr < 30 evaluates the comparison against every element simultaneously, returning a boolean array the same shape as arr. Using that boolean array directly as an index — arr[arr < 30] — selects only the elements where the mask is True, giving a filtered array containing just the qualifying values, in their original relative order.

## Exercise 42. Count Occurrences of Each Unique Element

**Concept:** np.unique(..., return_counts=True)

**Problem:** Count how many times each unique value appears in an array.

**Given:**
```
arr = [2, 3, 2, 5, 3, 3, 2, 5]
```

**Expected Output:**
```
Value 2 occurs 3 time(s)
Value 3 occurs 3 time(s)
Value 5 occurs 2 time(s)
```

**Hint:** return_counts=True makes np.unique() return TWO arrays: the sorted unique values, and their matching counts.

In [ ]:
import numpy as np

arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])
vals, counts = np.unique(arr, return_counts=True)
for v, c in zip(vals, counts):
    print(f"Value {v} occurs {c} time(s)")

**Explanation:** np.unique(arr) alone would return just the sorted distinct values. Passing return_counts=True additionally returns a second array of matching length, where each position holds the count of how many times the corresponding unique value appeared in the original array. zip(vals, counts) pairs each value with its count so both can be printed together in one loop.

## Exercise 43. Find the Intersection and Union of Two Arrays

**Concept:** np.intersect1d() and np.union1d()

**Problem:** Find both the shared elements and the combined unique elements of two arrays.

**Given:**
```
a = [1,2,3,5,7], b = [3,4,5,6,7]
```

**Expected Output:**
```
Intersection: [3 5 7]
Union: [1 2 3 4 5 6 7]
```

**Hint:** Both functions automatically sort their result and remove duplicates.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

intersection = np.intersect1d(a, b)
union = np.union1d(a, b)

print("Intersection:", intersection)
print("Union:", union)

**Explanation:** np.intersect1d(a, b) returns only the values present in BOTH arrays. np.union1d(a, b) returns every distinct value present in EITHER array, combined into one sorted, duplicate-free result. Both mirror standard mathematical set operations, applied directly and efficiently to NumPy arrays.

## Exercise 44. Transpose a Matrix

**Concept:** .T attribute / np.transpose()

**Problem:** Transpose a 2x2 matrix (flip it over its diagonal).

**Given:**
```
arr = [[1,2],[3,4]]
```

**Expected Output:**
```
[[1 3]
 [2 4]]
```

**Hint:** .T is a zero-cost VIEW of the transposed data — it doesn't copy or rearrange memory.

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
transposed_arr = arr.T
print(transposed_arr)

**Explanation:** Transposing flips a matrix over its main diagonal, turning rows into columns and columns into rows — element (i,j) moves to position (j,i). .T is a convenient shortcut attribute that gives a transposed VIEW of the array without physically copying or rearranging any underlying data; np.transpose(arr) is the equivalent function-call form producing the identical result.

## Exercise 45. Compute Eigenvalues and Eigenvectors

**Concept:** np.linalg.eig()

**Problem:** Compute the eigenvalues and eigenvectors of a 2x2 matrix.

**Given:**
```
A = [[4,2],[1,3]]
```

**Expected Output:**
```
Eigenvalues: [5. 2.]
Eigenvectors (columns): [[ 0.894 -0.707]
 [ 0.447  0.707]]
```

**Hint:** Each COLUMN of the eigenvector output (not each row) corresponds to one eigenvalue.

In [ ]:
import numpy as np

A = np.array([[4, 2],
              [1, 3]])

eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors (columns):\n", eigvecs)

**Explanation:** np.linalg.eig(A) computes A's eigenvalues (scalars) and eigenvectors (directions that A only stretches, never rotates) simultaneously, returning them as a pair. Each COLUMN (not row) of the eigvecs array is one eigenvector, and it corresponds to the eigenvalue at the matching position in eigvals — the first column pairs with the first eigenvalue, and so on. Eigenvalues and eigenvectors underpin PCA, stability analysis, and many other applications across data science and engineering.

## Exercise 46. Solve a System of Linear Equations

**Concept:** np.linalg.solve() for Ax = b

**Problem:** Solve the system x + 2y = 8 and 3x + 4y = 18.

**Given:**
```
A = [[1,2],[3,4]], b = [8,18]
```

**Expected Output:**
```
[2. 3.]  (x=2, y=3)
```

**Hint:** np.linalg.solve(A, b) is faster and more numerically stable than manually computing an inverse and multiplying.

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
b = np.array([8, 18])

solution = np.linalg.solve(A, b)
print(solution)

print(f"\nx = {solution[0]}, y = {solution[1]}")
print(f"Check: x + 2y = {solution[0] + 2*solution[1]}  (should be 8)")
print(f"Check: 3x + 4y = {3*solution[0] + 4*solution[1]}  (should be 18)")

**Explanation:** Writing the system as a matrix equation Ax = b, where A holds the coefficients and b holds the constants, np.linalg.solve(A, b) directly and efficiently computes the vector x satisfying that equation. This is both faster and more numerically stable than the mathematically equivalent alternative of computing np.linalg.inv(A) and multiplying it by b — solve() uses a more direct numerical method (LU decomposition) rather than the extra, error-prone step of forming an explicit inverse.

## Exercise 47. Create an 8x8 Checkerboard Pattern

**Concept:** alternating step-slicing to avoid an explicit loop

**Problem:** Create an 8x8 array with an alternating 0/1 checkerboard pattern.

**Given:**
```
no input
```

**Expected Output:**
```
An 8x8 grid alternating 0s and 1s in a checkerboard pattern
```

**Hint:** Two separate slice assignments — one for each color of square — together cover the whole checkerboard.

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

**Explanation:** Starting from an all-zero 8x8 grid, the first assignment (rows starting at 1, step 2; columns starting at 0, step 2) sets one family of alternating cells to 1. The second assignment (rows starting at 0, step 2; columns starting at 1, step 2) sets the complementary family. Together, these two step-sliced assignments cover every 'black square' of the checkerboard pattern in two vectorized operations, with no explicit nested loop over individual cells needed.

## Exercise 48. Find the Nearest Value in an Array

**Concept:** np.abs() + np.argmin() to find the closest match

**Problem:** Find the value in an array closest to a given target number.

**Given:**
```
arr = [1.5, 2.8, 3.2, 4.1], target = 3
```

**Expected Output:**
```
The value closest to 3 is: 2.8
```

**Hint:** np.argmin() finds the INDEX of the minimum absolute difference, not the difference itself.

In [ ]:
import numpy as np

arr = np.array([1.5, 2.8, 3.2, 4.1])
target_value = 3

index = np.abs(arr - target_value).argmin()
nearest_value = arr[index]
print(f"The value closest to {target_value} is: {nearest_value}")

**Explanation:** arr - target_value is a vectorized subtraction, giving each element's signed distance from the target. np.abs() converts every distance to a positive magnitude, since 'closest' should ignore direction. .argmin() then returns the INDEX of the smallest value in that distance array — not the distance itself — which is used to look back into the original arr and retrieve the actual nearest value. Here, 2.8 (distance 0.2) narrowly beats 3.2 (distance 0.2 as well — checking precisely, |2.8-3|=0.2 and |3.2-3|=0.2, a tie broken by argmin() returning the FIRST occurrence of the minimum).

## Exercise 49. Convert to an Object Array

**Concept:** dtype='object' for mixed-type storage

**Problem:** Create an array that can hold mixed Python types (unlike a standard NumPy array).

**Given:**
```
a numeric array, later mixed with a string element
```

**Expected Output:**
```
[1 'a' 3 4 5]
object
```

**Hint:** A standard NumPy array can only hold ONE consistent dtype — an object array is the escape hatch for mixed types.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

obj_arr = np.empty(arr.size, dtype='object')
obj_arr[:] = arr

obj_arr[1] = 'a'
print(obj_arr)
print(obj_arr.dtype)

**Explanation:** A standard NumPy array requires every element to share the same fixed dtype (all int64, all float64, etc.), which is exactly what enables its fast, memory-efficient, vectorized operations. np.empty(arr.size, dtype='object') instead creates an array whose elements are generic Python object references, similar to a plain Python list — able to hold a genuine mix of types like the integer 1 and the string 'a' side by side, at the cost of losing most of NumPy's performance advantages for that array.

## Exercise 50. Descriptive Statistics Summary (Mean, Median, Std, Variance, Percentiles)

**Concept:** a fuller statistical summary combining several np.* functions

**Problem:** Compute a fuller statistical summary of an array: mean, median, std, variance, and quartiles.

**Given:**
```
arr = np.array([10, 20, 30, 100, 200, 300])
```

**Expected Output:**
```
Mean, Median, Std, Variance, and 25th/75th percentiles
```

**Hint:** np.var() is simply np.std() squared; np.percentile(arr, q) generalizes the median (which is the 50th percentile).

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 100, 200, 300])

mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
variance = np.var(arr)
q25 = np.percentile(arr, 25)
q75 = np.percentile(arr, 75)

print(f"Mean              : {mean}")
print(f"Median            : {median}")
print(f"Standard Deviation: {std}")
print(f"Variance          : {variance}")
print(f"25th percentile   : {q25}")
print(f"75th percentile   : {q75}")
print(f"\nVariance == Std**2: {np.isclose(variance, std ** 2)}")

**Explanation:** This extends the mean/median/std computation from Exercise 21 with two more common descriptive statistics. np.var() computes the variance — the average of the squared deviations from the mean — which is mathematically always equal to the standard deviation squared (confirmed by the closing check). np.percentile(arr, q) generalizes the idea of a median: the 50th percentile IS the median, while the 25th and 75th percentiles (the first and third quartiles) mark the boundaries containing the middle 50% of the data, useful for understanding a distribution's spread beyond just its center.