In [2]:
# create model class
import torch
import torch.nn as nn

In [19]:


class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
                                  nn.Linear(num_features, 3),
                                  nn.ReLU(),
                                  nn.Linear(3,2),
                                  nn.LeakyReLU(),
                                  nn.Linear(2, 1),
                                  nn.Sigmoid()
                                )

  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
modelobj = Model(num_features=5)

modelobj.forward(features)

modelobj(features)

In [9]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out =self.linear2(out) 
    out = self.sigmoid(out)
    return out


In [3]:
features = torch.rand(10,5)

In [4]:
type(features)

torch.Tensor

In [21]:
print(features)

tensor([[3.2178e-01, 1.9316e-01, 8.7435e-01, 1.1137e-01, 4.2944e-01],
        [8.8054e-01, 4.5325e-01, 4.5275e-01, 7.0529e-01, 1.2343e-01],
        [9.2189e-02, 1.8826e-01, 1.6224e-01, 1.8954e-05, 6.5859e-01],
        [8.1620e-01, 3.2587e-01, 1.1337e-01, 7.8121e-03, 2.0941e-01],
        [4.3035e-01, 2.7953e-01, 3.5781e-01, 4.5604e-01, 2.7242e-01],
        [9.6742e-01, 5.2703e-01, 1.6474e-01, 3.6226e-01, 9.2491e-01],
        [1.7419e-01, 8.2820e-01, 1.3560e-02, 9.9794e-01, 7.9120e-02],
        [5.3072e-01, 7.8531e-01, 1.7986e-01, 8.5549e-01, 4.9479e-01],
        [3.5158e-01, 2.8649e-01, 1.7284e-01, 2.5639e-01, 9.0787e-01],
        [8.3130e-01, 1.0310e-01, 6.4945e-01, 5.2193e-01, 1.0256e-02]])


In [ ]:
# create dataset


# create model
model = Model(5)

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6382],
        [0.6291],
        [0.6303],
        [0.6273],
        [0.6326],
        [0.6119],
        [0.6346],
        [0.6249],
        [0.6213],
        [0.6338]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
#model.linear1.weight   # This will be used when we have defined the layers as separate attributes in the __init__ method. However, since we are using nn.Sequential to define the network, 
# we need to access the layers through the sequential container.
#print(model.linear1.bias)
model.network[2].weight  # Based on the network structure the second linear layer is at index 2


Parameter containing:
tensor([[ 0.4800, -0.0515, -0.1938],
        [-0.5050,  0.3967, -0.0212]], requires_grad=True)

In [15]:
!pip install torchinfo

^C


  Using cached torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Using cached torchinfo-1.8.0-py3-none-any.whl (23 kB)



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [25]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 2]                   8
│    └─LeakyReLU: 2-4                    [10, 2]                   --
│    └─Linear: 2-5                       [10, 1]                   3
│    └─Sigmoid: 2-6                      [10, 1]                   --
Total params: 29
Trainable params: 29
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [4]:
import sys
print(sys.executable)

h:\01_Training\ContentSlides_AgenticAI\Code\all_envs\pt_env\Scripts\python.exe


In [5]:
import sys
!{sys.executable} -m pip show torchinfo