In [1]:
import numpy as np

# Creating arrays from existing data


### **Creating** an array from a list

In [2]:
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)

**Think:** what shape do we expect the array to be? How can we confirm if our expectation is met?

## Creating an array from multiple lists

Imagine that we have not one, but three lists, and we want to make an array where each list is a row.

In [3]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

arr = np.array([row1, row2, row3])

**Think:** Before we inspect the array: how many rows and columns do we expect it to have?

We can also make an array where the lists correspond to _columns_.


In [4]:
col1 = [1, 4, 7]
col2 = [2, 5, 8]
col3 = [3, 6, 9]

arr = np.array([col1, col2, col3]).T

**Think:** What do you think the `.T` method does? How can we verify this?

# Creating arrays from a shape or value

## Creating an array where all values are $x$

Let's say we want to make an array where all values are 3. There is a handy function that will help us do this.

In [5]:
my_value = 5
size = (3, 4)
arr_X = np.full(size, my_value)

There are some helpful functions for special cases, like making an array that's all zeros or all ones.

In [6]:
arr_zero = np.zeros(size)
arr_one = np.ones(size)

## Creating an array full of random numbers

There is another function that will fill up an array of a specified size with randomly generated numbers.

In [7]:
rows = 2
cols = 3
arr_random = np.random.rand(rows, cols)

## Creating an array with numbers only on the diagonal

Sometimes we will want an array where every value is 0, _except_ along the diagonal-this is especially common in certain linear algebra applications. Luckily, there's also a function for this!


In [8]:
size = 4
diagonal_values = [1, 2, 3, 4]
arr_diagonal = np.diag(diagonal_values)

## Creating arrays according to a sequence

Let's say we want to create an array of numbers that go from 0 to 1000, with a stepsize of 1. Yet again, `numpy` has us covered!

In [9]:
arr = np.arange(0, 1001, 1)

And there's even simpler shorthand for when we want to start at 0 and go up by a stepsize of 1:

In [10]:
arr = np.arange(1001)


# Arrays with a specified data type
Recall that there are several numeric data types in Python, like `int` and `float`. In `numpy`, these also show up (although with some `numpy`-specific nuances, which we'll point out later). We can specify that array be created with a certain type.

In [11]:
arr_int = np.array(my_list, dtype = "int")
arr_int

array([1, 2, 3, 4, 5])

In [12]:
arr_float = np.array(my_list, dtype = "float")
arr_float

array([1., 2., 3., 4., 5.])

This way of specifying type works for other helper functions for creating arrays.

In [13]:
arr_zero_int = np.zeros((2,2), dtype = "float")
arr_zero_int

array([[0., 0.],
       [0., 0.]])

# Modifying values in an array
We can overwrite the values in an array by assigning a new value with the `=` operator.

In [14]:
arr

array([   0,    1,    2, ...,  998,  999, 1000])

In [15]:
arr[0] = -1

In [16]:
arr

array([  -1,    1,    2, ...,  998,  999, 1000])