In [ ]:
import numpy as np

## Accessing elements in an array with indexing

Let's begin by creating an array.

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


How would we access a value based on its position- for example: _the second element in row 2_?

In [ ]:
arr[1,1]

6

Remember- indexes start at 0 in Python! So you might have to translate between how you count rows and columns in your head, and how you would do write it in Python.

Let's try another. Say we want to get the element in the third row, fourth column.

In [ ]:
arr[2,3]

12

## Slicing

Slicing is a way of using indexing to get whole rows or columns out of an array. If we want to get a whole row, there's a simple syntax for that.

In [ ]:
arr[1]

array([5, 6, 7, 8])

This syntax extends nicely if we want to return multiple rows. The code below will give us the first two rows of the array.  But keep an eye on the way we're indexing rows- do you notice anything?

In [ ]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

To access **columns**, the syntax is very similar. Notice that we're using a new symbol `:` as a placeholder where our row indices would usually go.

In [ ]:
arr[:, 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

Based on the behavior above, what do you think the `:` sign means? Let's experiment- what if we had used a number there?

In [ ]:
arr[1, 0:2]

array([5, 6])

## Negative indexing

Something special in Python is that we can use a _negative_ index. What could that possibly mean? Let's take a look.

In [ ]:
arr[-1]

array([ 9, 10, 11, 12])

What does that do?  Next up, what do you think the following code will do? Think about it and then run it.

In [ ]:
arr[-2]

How about this code?

In [ ]:
arr[:, -1]

array([ 4,  8, 12])

## Caution when modifying slices!
When you do basic slicing operations as above, `numpy` creates something called a _view_ rather than a _copy_ of the original array.

In [ ]:
arr

In [ ]:
my_slice = arr[:, -1]
my_slice

Let's see what happens when we modify a value of `my_slice`.

In [ ]:
my_slice[0] = 1000
my_slice

array([1000,    8,   12])

In [ ]:
arr

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

What's happening? The variable `my_slice` is pointing to the same data as `arr`! We can verify this by checking the `.base` attribute of `my_slice` (remember: all the attributes are [described in the docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)).

In [ ]:
my_slice.base

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

If you're not careful, this can lead to some big headaches. So if you need to make a slice that is truly a new copy of your original array, call the array's `copy()` method.

In [ ]:
slice_copy = arr[:, -1].copy()
slice_copy

array([1000,    8,   12])

In [ ]:
slice_copy[1] = 0
slice_copy

array([1000,    0,   12])

In [ ]:
arr

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

## Indexing with logical operators
We can pull values out of an array based on a condition defined with Python logical operators. What do you think this does?

In [ ]:
arr > 8

array([[False, False, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [ ]:
arr[arr > 8]

array([1000,    9,   10,   11,   12])

We can use this kind of indexing to conveniently locate and then modify certain values of an array. For example, what if we want to set all the values _greater_ than 8 to 8?

_*Note: This is called "windsorizing" and it is a technique in data analysis that is used to condense the range of numbers we are analyzing._

In [ ]:
arr[arr>8] = 8
print(arr)

[[1 2 3 8]
 [5 6 7 8]
 [8 8 8 8]]


If there are multiple conditions we want to filter by, we might have to be careful about our syntax.

In [ ]:
compound_condition = (arr % 2 == 1) & (arr > 4)
arr[compound_condition]

array([5, 7])

Note that indexing via logic creates a new copy of data rather than a view.

In [ ]:
my_subset = arr[arr<4]
my_subset

array([], dtype=int64)

In [ ]:
my_subset.base